// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiZOs7aGRb8OjRQ9SyfutjencKylSDV-E',
    appId: '1:997704612092:web:0de4e4fbf7779c5c41bf79',
    messagingSenderId: '997704612092',
    projectId: 'fruits-hub-e625e',
    authDomain: 'fruits-hub-e625e.firebaseapp.com',
    storageBucket: 'fruits-hub-e625e.firebasestorage.app',
    measurementId: 'G-TQ63V5LS7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlfe0POxnmNsRTNJEly5JNpBwOKHxJ7Bs',
    appId: '1:997704612092:android:b4ab7f89b5593b6941bf79',
    messagingSenderId: '997704612092',
    projectId: 'fruits-hub-e625e',
    storageBucket: 'fruits-hub-e625e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjYMICp-w-GrkcmabEtudgnGJRwfdamVM',
    appId: '1:997704612092:ios:011a52c679f2f6cb41bf79',
    messagingSenderId: '997704612092',
    projectId: 'fruits-hub-e625e',
    storageBucket: 'fruits-hub-e625e.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjYMICp-w-GrkcmabEtudgnGJRwfdamVM',
    appId: '1:997704612092:ios:011a52c679f2f6cb41bf79',
    messagingSenderId: '997704612092',
    projectId: 'fruits-hub-e625e',
    storageBucket: 'fruits-hub-e625e.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiZOs7aGRb8OjRQ9SyfutjencKylSDV-E',
    appId: '1:997704612092:web:4e3234069e9e05f941bf79',
    messagingSenderId: '997704612092',
    projectId: 'fruits-hub-e625e',
    authDomain: 'fruits-hub-e625e.firebaseapp.com',
    storageBucket: 'fruits-hub-e625e.firebasestorage.app',
    measurementId: 'G-TFYHXMTG0F',
  );
}
